# Generated by Django 3.2 on 2023-04-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230414_1839'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_users',
        ),
    ]
